cmake_minimum_required(VERSION 4.0)
project(TPPOO2)

set(CMAKE_CXX_STANDARD 20)

add_executable(TPPOO2 main.cpp
        Mapa/Jardim.cpp
        Mapa/Jardim.h
        Planta/Planta.cpp
        Planta/Planta.h
        Solo/Solo.cpp
        Solo/Solo.h
        Comandos/Listar/Listar_Area.cpp
        Comandos/Listar/Listar_Area.h
        Comandos/Comandos.cpp
        Comandos/Comandos.h
        Settings/Settings.h
        Settings/Settings.h
        Ferramentas/Ferramentas.cpp
        Ferramentas/Ferramentas.h
        Simulador/Simulador.cpp
        Simulador/Simulador.h
        Comandos/CriarMapa/CriarMapa.cpp
        Comandos/CriarMapa/CriarMapa.h
        InterfaceUtilizador/InterfaceUtilizador.cpp
        InterfaceUtilizador/InterfaceUtilizador.h
        Comandos/Listar/Lplantas.h
        Comandos/Listar/Lplantas.cpp
        Comandos/Acoes/Pega.h
        Comandos/Acoes/Colhe.h
        Comandos/Acoes/Avanca.h
        Comandos/Acoes/Plantar.h
        Comandos/Acoes/Colhe.cpp
        Comandos/Acoes/Avanca.cpp
        Comandos/Acoes/Largar.cpp
        Comandos/Acoes/Pega.cpp
        Comandos/Acoes/Plantar.cpp
        Comandos/Listar/Ajuda.cpp
        Comandos/Listar/Lista_Ferramentas.cpp
        Comandos/Listar/Lplanta.cpp
        Comandos/Listar/Lsolo.cpp
        Comandos/Movimento/Baixo.cpp
        Comandos/Movimento/Cima.cpp
        Comandos/Movimento/Cima.h
        Comandos/Movimento/Direita.cpp
        Comandos/Movimento/Esquerda.cpp
        Jardineiro/Jardineiro.cpp
        Jardineiro/Jardineiro.h
        Comandos/Fim/Fim.cpp
        Comandos/Fim/Fim.h
        Comandos/Acoes/Entra.cpp
        Comandos/Acoes/Entra.h
        Comandos/Acoes/Sair.cpp
        Comandos/Acoes/Sair.h
        Ferramentas/Adubo.cpp
        Ferramentas/Adubo.h
        Ferramentas/Drone.cpp
        Ferramentas/Drone.h
        Ferramentas/TesouraDePodar.cpp
        Ferramentas/TesouraDePodar.h
        Ferramentas/Regador.cpp
        Ferramentas/Regador.h
        Ferramentas/Regador.cpp
        Comandos/Gerais/Grava.cpp
        Comandos/Gerais/Grava.h
        Comandos/Gerais/Recupera.cpp
        Comandos/Gerais/Recupera.h
        Comandos/Gerais/Apaga.cpp
        Comandos/Gerais/Apaga.h
        Comandos/Gerais/Executa.cpp
        Comandos/Gerais/Executa.h
        Planta/Cacto.cpp
        Planta/Cacto.h
        Planta/Roseira.cpp
        Planta/Roseira.h
        Planta/ErvaDaninha.cpp
        Planta/ErvaDaninha.h
        Planta/Maracuja.cpp
        Planta/Maracuja.h
        Comandos/Acoes/Compra.cpp
        Random/Random.cpp
        Random/Random.h
        Comandos/Acoes/Usa.cpp
        Comandos/Acoes/Usa.h)
